[project]
name = "JiboTools"

[tool.pyside6-project]
files = [
	"main_panel.py",
	"form.ui",
	"gui/__init__.py",
	"gui/main_panel.py",
	"gui/installer_gui.py",
	"gui/updater_gui.py",
	"gui/process_runner.py",
	"gui/terminal_helper.py",
	"gui/tool_runner.ui",
	"gui/tool_runner_window.py",
	"gui/ui_loader.py",
	"gui/Assets/Jibo/JiboFaceForward.png",
	"gui/Assets/Jibo/NoJiboConnected.png",
]
